mysql:
  image: mysql
  container_name: mysql
  environment:
    TERM: xterm
    APP_ENV: dev
    MYSQL_DATABASE: 'test_db'
    MYSQL_USER: 'root'
    MYSQL_PASSWORD: 'root1234'
    MYSQL_ROOT_PASSWORD: root
  ports:
    - "3306:3306"
  volumes:
    - ~/db/mysql:/var/lib/mysql
    - ./config.cnf:/etc/mysql/conf.d/config.cnf
    - ./init-dump:/docker-entrypoint-initdb.d
  container_name: mysql



  # Enter in the docker container
  # $ docker exec -it mysql bash
  # Connect to mysql service, and enter in password 12345678
  # $ mysql -h 127.0.0.1 -u root -P 3306 -p

    # you can stop service by the command
  # $ docker stop mysql
  # you can start service by the command
  # $ docker start mysql
  # you can restart service by the command
  # $ docker restart mysql